const plantImages = {
    peashooter: (() => { const img = new Image(); img.src = '../assets/png/peashooter.png'; return img; })(),
    sunflower: (() => { const img = new Image(); img.src = '../assets/png/sunflower.png'; return img; })(),
    spread: (() => { const img = new Image(); img.src = '../assets/png/peasecod.png'; return img; })(),
    torchwood: (() => { const img = new Image(); img.src = '../assets/png/torchwood.png'; return img; })(),
    watermelon: (() => { const img = new Image(); img.src = '../assets/png/watermelon.png'; return img; })(),
    mimic: (() => { const img = new Image(); img.src = '../assets/png/mimic.png'; return img; })(),
    bomber: (() => { const img = new Image(); img.src = '../assets/svg/bomber.svg'; return img; })(),
    iced_coconut: (() => { const img = new Image(); img.src = '../assets/png/iced-coconut.png'; return img; })(),
    trumpet: (() => { const img = new Image(); img.src = '../assets/svg/trumpet.svg'; return img; })(),
    pine_shooter: (() => { const img = new Image(); img.src = '../assets/svg/pine-shooter.svg'; return img; })(),
    gold_bloom: (() => { const img = new Image(); img.src = '../assets/png/gold-blooms.png'; return img; })(),
    spiky_pumpkin: (() => { const img = new Image(); img.src = '../assets/svg/spiky-pumpkin.svg'; return img; })(),
    jalapeno_pair: (() => { const img = new Image(); img.src = '../assets/svg/jalapeno-pair.svg'; return img; })(),
    reshaper: (() => { const img = new Image(); img.src = '../assets/svg/reshaper.svg'; return img; })(),
    time_machine: (() => { const img = new Image(); img.src = '../assets/svg/time-machine.svg'; return img; })(),
    laser_shroom: (() => { const img = new Image(); img.src = '../assets/svg/laser-shroom.svg'; return img; })(),
    windmill: (() => { const img = new Image(); img.src = '../assets/svg/windmill.svg'; return img; })(),
    vine_trap: (() => { const img = new Image(); img.src = '../assets/svg/vine-trap.svg'; return img; })(),
    electrode_cherry: (() => { const img = new Image(); img.src = '../assets/svg/electrode-cherry.svg'; return img; })(),
    wild_gatling: (() => { const img = new Image(); img.src = '../assets/png/wild-gatling.png'; return img; })(),
    ninja_nut: (() => { const img = new Image(); img.src = '../assets/png/ninja-nut.png'; return img; })(),
    citron: (() => { const img = new Image(); img.src = '../assets/png/citron.png'; return img; })(),
    corn_homing: (() => { const img = new Image(); img.src = '../assets/svg/corn-homing.svg'; return img; })(),
    corn_gatling: (() => { const img = new Image(); img.src = '../assets/svg/corn-gatling.svg'; return img; })(),
};

const zombieImages = {
    normal: (() => { const img = new Image(); img.src = '../assets/png/zombie.png'; return img; })(),
    bucket: (() => { const img = new Image(); img.src = '../assets/png/bucket-zombie.png'; return img; })(),
    exploder: (() => { const img = new Image(); img.src = '../assets/svg/exploder-zombie.svg'; return img; })(),
    football: (() => { const img = new Image(); img.src = '../assets/png/rugby-zombie.png'; return img; })(),
    football_forward: (() => { const img = new Image(); img.src = '../assets/png/football-forward.png'; return img; })(),
    fisher: (() => { const img = new Image(); img.src = '../assets/svg/fisher-zombie.svg'; return img; })(),
    gargantuar: (() => { const img = new Image(); img.src = '../assets/png/gargantuar.png'; return img; })(),
    priest: (() => { const img = new Image(); img.src = '../assets/svg/priest-zombie.svg'; return img; })(),
};
